### ISSUE TITLE
Error: Cannot find module 'JPush/JPush.js'

### ISSUE THREAD

**Issue by gclsoft** [jpush/jpush-api-nodejs-client#10]
``` var JPush = require("../lib/JPush/JPush.js");```
Error: Cannot find module 'JPush/JPush.js'
I've npm i the library
```
,"jpush-sdk":"*"
```

**Comment by xiezefan** [comment]
Sorry, 测试后忘记替换回来了。
麻烦你修改一下，用 `var JPush = require("jpush-sdk");` 来引入jpush

**Comment by JcmeLs** [comment]
@xiezefan Hi,这意思是不是lib下的JPush文件可以不用加入到自己的项目中，直接var JPush = require('jpush-sdk')就行了是吧
