### ISSUE TITLE
为什么所有error都是直接throw的，可以考虑在链式调用末尾加上 .catch(err) 吗？

### ISSUE THREAD

**Issue by plusmancn** [jpush/jpush-api-nodejs-client#12]
框架内部代码写得也有点啰嗦，比如 _request 最后发送请求，其实 request 库有method参数的，没必要用四个if，当然还有json参数，不能用eval，略危险。

还有很多代码细节，感觉写得有点死板。

最重要的是，错误处理机制，throw 用得太随意了。

**Comment by xiezefan** [comment]
批评得有理，写这个库的时候，刚从java转过来，还不太熟悉node的异常处理约定。

因为我们公司并没有专职写nodejs的同事，所以这个库也是我兼职维护的，如果你有好的建议，也非常欢迎提供Pull Request。

**Comment by plusmancn** [comment]
^_^，其实我也是新手，对于框架层面也还有很多不明白的地方。
最近由于业务需求需要对推送做一些优化，就用上了这个sdk。
咨询了几个资深前辈，正在对这个sdk做一些修改。

*  用tj的debug模块，替代现有log输出方式
*  错误统一在链式调用末尾抛出，更改Error为标准格式，并带上错误栈，方便和现有日志系统集成
*  统一的参数检测方法。
*  添加推送任务池、批量推送速率控制、守护进程（消费者）
*  尝试建立重发机制（不确定能否实现）

会先在内部运行一段时间，如果状态良好，会考虑提供Pull Request。
= = 心里好没底~~~~~~~
