### ISSUE TITLE
msg_id类型问题

### ISSUE THREAD

**Issue by wmzy** [jpush/jpush-api-nodejs-client#13]
[rest api](http://docs.jpush.cn/display/dev/Push-API-v3)文档给的返回示例是string类型的，为什么这里会转成int类型？

**Comment by xiezefan** [comment]
你好，谢谢你的反馈。

我们的NodeJS Client并没有对返回的Response进行处理，是Node Parse JSON的时候自己把msg_id转成int，不过我们内部定义msgId是一个64位的int值，所以这样也不会用问题。

如果你有需要的话，可以手动把msg_id转成string类型

**Comment by wmzy** [comment]
Node Parse JSON的时候**并没有**把msg_id转成int,而是你们的文档写错了。。。。

**Comment by xiezefan** [comment]
你好，我检查了下， 文档没问题，返回的确是字符串。 你也可以试一试。

```
curl --insecure -X POST -v https://api.jpush.cn/v3/push -H "Content-Type: application/json" -u "7d431e42dfa6a6d693ac2d04:5e987ac6d2e04d95a9d8f0d1" -d '{"platform":"all","audience":"all","notification":{"alert":"Hi,JPush !","android":{"extras":{"android-key1":"android-value1"}},"ios":{"sound":"sound.caf","badge":"+1","extras":{"ios-key1":"ios-value1"}}}}'
```

**Comment by wmzy** [comment]
[这个文档](https://github.com/jpush/jpush-api-nodejs-client/blob/master/doc/api.md)里写的是int，其实是String，请检查一下。
我不是说[REST API 文档](http://docs.jpush.cn/display/dev/Push-API-v3)错了。
