### ISSUE TITLE
貌似不好使了

### ISSUE THREAD

**Issue by feit** [jpush/jpush-api-nodejs-client#16]
通过jpush的管理后台能发出去消息，通过这个就不行，请检查一下。

**Comment by crapthings** [comment]
后台能发，用 node client api 收不到，官方检查一下啊

**Comment by helperhaps** [comment]
@crapthings @Feit  刚刚测试代码是可以正常运行的

**Comment by crapthings** [comment]
@helperhaps 

isDebug: false

这个参数和 开发模式 生产模式 有没有关系？

**Comment by helperhaps** [comment]
@crapthings  刚刚稍稍看了一下代码，这个参数只是用来确认是否打印 log 的，和环境没有关系。我是直接运行 README 上的示例，结果 android 手机收到了推送，所以你所谓的“收不到”应该是你自己的实现或者其他哪里的问题。

**Comment by crapthings** [comment]
ios
部分可能需要这个

    setOptions: {
        apns_production: true
    }

来指定生产环节

**Comment by helperhaps** [comment]
是的，你可以先使用 Android 机来测试，服务端的话，Android 方面是比较简单的，只要 Android 没有问题的话，服务端就不会有太大问题。

**Comment by godion** [comment]
推送iOS生产环境收不到消息，Android怎么都能收到消息

**Comment by helperhaps** [comment]
@godion 这种问题请到这里寻找答案 [我是链接](http://community.jiguang.cn/search?q=iOS%20%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83)

**Comment by godion** [comment]
谢，
.setOptions(null, 60, null, true)
这边改成true可以，默认不写是dev环境
