### ISSUE TITLE
增加代理推送功能

### ISSUE THREAD

**Issue by chenyishun** [jpush/jpush-api-nodejs-client#20]
现在大部份部署后台程序的服务器都没有上网功能，需要走代理才能发送推送消息。为了解决这个问题，我是自己修改了SDK的代码，不想自己维护一套SDK的代码，希望jpush-api-client在后续的版本中，支持该功能，如果有需要我可以提交我修改的代码。

**Comment by lhw5123** [comment]
可以提交一个 PR，之后我这边测试下，如果没有问题的话，就直接加在新版本里。: )

**Comment by helperhaps** [comment]
已发版本支持
