### ISSUE TITLE
ios推送，默认options['apns_production'] = false

### ISSUE THREAD

**Issue by lesonli** [jpush/jpush-api-nodejs-client#21]
代码中默认为推送开发环境，
`options['apns_production'] = false`
文档中说明如下：
如果目标平台为 iOS 平台 需要在 options 中通过 apns_production 字段来设定推送环境。True 表示推送生产环境，False 表示要推送开发环境； 如果不指定则为推送生产环境

按照文档开发容易误导，建议更新文档

**Comment by lhw5123** [comment]
确实是这样，感谢指正。: )
