### ISSUE TITLE
npm 安装jpush-sdk 导入出错

### ISSUE THREAD

**Issue by liyikun** [jpush/jpush-api-nodejs-client#22]
项目中 import Jpush from 'jpush-sdk'
编译通过，但是打开网页，控制台提示

fs.readFileSync is not a function

**Comment by lhw5123** [comment]
fs.readFileSync 是 node.js 的一个自带方法，可以看看是不是环境的问题。还有 node.js 程序为什么会需要打开网页呢？: )
