### ISSUE TITLE
IOS推送无法自定义title的问题

### ISSUE THREAD

**Issue by CRAZYFAKE** [jpush/jpush-api-nodejs-client#28]
问题：ios无法自定义标题
原因：在查找了api之后，与node.js SDK源码进行比较，发现一个比较明显的问题，如下：
https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/
![image](https://cloud.githubusercontent.com/assets/5547478/21974214/5cf98b86-dc00-11e6-8c5f-5fc1cff75eba.png)
api里面alert关键字不止是string类型，还可以是JSON Object，但是在最新的sdk源码中是不允许JSON Objet的
![image](https://cloud.githubusercontent.com/assets/5547478/21974298/ed5b9fde-dc00-11e6-9142-3f040168a329.png)
所以我就只能去更改源码，然后不能以模块node_modules的形式引入到项目中了。
 jpush-sdk版本是最新的：
![image](https://cloud.githubusercontent.com/assets/5547478/21974372/47ce37c4-dc01-11e6-8db3-ec7e661bd3d8.png)

**Comment by lhw5123** [comment]
已更新。: )

**Comment by CRAZYFAKE** [comment]
好的。

**Comment by CRAZYFAKE** [comment]
更新了3.3.4以后
![ed5b9fde-dc00-11e6-9142-3f040168a329](https://cloud.githubusercontent.com/assets/5547478/22909686/88fe44be-f290-11e6-94b4-99e8546dffc8.png)
把alert的object类型判断删除了，导致我们在上线的时候排查了很久。对此我很困惑。希望能够得到解决。

**Comment by CRAZYFAKE** [comment]
3.3.3版本：
![image](https://cloud.githubusercontent.com/assets/5547478/22909768/01c2c302-f291-11e6-962d-a59b5ac8a5fc.png)

3.3.4版本：
![image](https://cloud.githubusercontent.com/assets/5547478/22909825/4fb1074a-f291-11e6-8843-564c70e9e90f.png)

**Comment by lhw5123** [comment]
抱歉，可尝试更新版本。

**Comment by chaochao-zhang** [comment]
目前我们版本更新到了 4.0.3，程序支持object类型的alert，文档alert类型依然是 String

**Comment by chaochao-zhang** [comment]
https://github.com/jpush/jpush-api-nodejs-client/blob/master/doc/api.md
