### ISSUE TITLE
Is 'sms_message：短信补充' supported?

### ISSUE THREAD

**Issue by johnwook** [jpush/jpush-api-nodejs-client#30]
- [Push API v3](https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#) has sms_message parameter
- As far as I know, `sms_message` request parameter is not supported by this client SDK.
- Is this right?, do you have any plan to support this request parameter?

**Comment by lhw5123** [comment]
[v3.3.2](https://github.com/jpush/jpush-api-nodejs-client/releases) has supported. : )
