### ISSUE TITLE
关于node.js推送自定义消息

### ISSUE THREAD

**Issue by CRAZYFAKE** [jpush/jpush-api-nodejs-client#31]
在官方api中我发现是可以设置自定义消息的，
![qq 20170206170420](https://cloud.githubusercontent.com/assets/5547478/22640622/774fd2f8-ec8e-11e6-9cd9-3357c52af0a9.png)
我想用node.js api推送自定义消息，请问如何设置呢。

**Comment by lhw5123** [comment]
与通知类似，只是 setNotification 换为 setMessage。
参数：
![c116d0f6-6d23-4fdf-be6c-ea078725ded5](https://cloud.githubusercontent.com/assets/6531354/22642455/ae1a9ca8-ec95-11e6-8304-99ce6f00bbec.png)
![aec1671a-fe4f-4102-9156-40bcbaaa88b7](https://cloud.githubusercontent.com/assets/6531354/22642206/b7b9dee6-ec94-11e6-9199-acea648a1e3d.png)
