### ISSUE TITLE
node 推送显示成功，但是手机并没有接受到推送

### ISSUE THREAD

**Issue by Xing-He** [jpush/jpush-api-nodejs-client#32]
- node + react-native
- react-native : 0.41.2
- IOS推送

我在控制台发送推送是可以接收到推送的，通过API调用则不可以

node后端调用该方法：通过设置别名发送  
```js
pushIOS:function(push_data, callback){
    client.push()
    .setPlatform('ios') 
    .setAudience(JPush.alias(push_data.alias)) 
    .setNotification('Alert_name',JPush.ios(push_data.message)) 
    .setOptions(null, 60) 
    .send(function(err, res) {
      if (err) return callback(err)
      callback(err,res)
    });
  }
```

终端输出如下：
```
Push URL :https://api.jpush.cn/v3/push

Body :{"options":{"sendno":239681430,"time_to_live":60,"apns_production":true},"notification":{"ios":{"alert":"2rwerwe1","sound":"","badge":"+1"},"alert":"Alert_name"},"audience":{"alias":["1"]},"platform":["ios"]}
Headers :{"User-Agent":"JPush-API-NodeJS-Client","Connection":"Keep-Alive","Charset":"UTF-8","Content-Type":"application/json"}
Method :POST
Times/MaxTryTimes : 1/3
Success, response : {"sendno":"239681430","msg_id":"7827150492"}
```

我看到`apns_production:true`，我是测试环境，这个属性在哪里设置的，跟这个有关吗？

**Comment by Xing-He** [comment]
通过`setOptions(null, 60 ,null, false)`设置` apns_production:false`ios也没接收到推送

**Comment by Xing-He** [comment]
我通过`setAudience(JPush.registration_id('id')) `设置注册id的方式接收到了推送，难道是我设置别名没有作用？？？这该在哪里查看呢

**Comment by lhw5123** [comment]
可以通过 getDeviceTagAlias(registrationId, callback) 来看看设备的别名有没有设置上。
或者可以把未收到消息的 msg_id 和未收到消息设备的 registration_id，在我们[社区](https://community.jiguang.cn/)上发帖，会帮忙查一下具体是什么原因。

**Comment by Xing-He** [comment]
已解决：可能跟我设置别名命名规则错误有关吧，后面没动就好了

[`jpush-react-native #145`](https://github.com/jpush/jpush-react-native/issues/145)
