### ISSUE TITLE
为什么要使用 eval

### ISSUE THREAD

**Issue by tiant167** [jpush/jpush-api-nodejs-client#33]
为什么要 eval？这样可以随便挂后门吧？

```javascript
return callback(null, eval('(' + body + ')'));
```

https://github.com/jpush/jpush-api-nodejs-client/blob/4409fecd6e4f3ed9fe71c6e015ad721dbcf4b732/lib/JPush/JPush.js#L448

**Comment by lhw5123** [comment]
是个历史遗留问题，已修复。: )

**Comment by RenzHoly** [comment]
这样改还是有可能抛异常的吧？

**Comment by lhw5123** [comment]
@RenzHoly 服务器端有做校验的，所以是可以保证数据为有效 JSON 的。: )

**Comment by RenzHoly** [comment]
包被改了，网络不好，你们服务器逻辑出错，都会出错吧？还是client判断一下比较好
刚才你们的这个错误就把我们的服务弄垮了

**Comment by lhw5123** [comment]
@RenzHoly eval 导致的？

**Comment by RenzHoly** [comment]
是的

**Comment by lhw5123** [comment]
@RenzHoly 很抱歉， client 我先加上判断，明天再详细排查一下。: (
