### ISSUE TITLE
node SDK，如何是设置客户端角标自增

### ISSUE THREAD

**Issue by KsssAlleria** [jpush/jpush-api-nodejs-client#38]
nodejs SDK ios推送是有提供这个字段，但是文档是这样描述的 “badge字段 接受参数 如果为 null，表示不改变角标数字；否则把角标数字改为指定的数字；为 0 表示清除”。并没有+1的参数

**Comment by helperhaps** [comment]
@KsssAlleria 那你可以传递 +1 试一下
