### ISSUE TITLE
 tag, alias 不能同时在 .setAudience 的参数里

### ISSUE THREAD

**Issue by nodejscss** [jpush/jpush-api-nodejs-client#41]
var tag = ['a@d.com', 'b@d.com', 'c@d.com'];
var alias = ['a@d.com', 'b@d.com', 'c@d.com'];
.setAudience(JPush.tag(tag), JPush.alias(alias.join(',')) // 不正常，全部无效

// ---------------------------------------------------------------------------

.setAudience(JPush.alias('a@d.com')) // 正常
.setAudience(JPush.tag('b@d.com')) // 也正常

.setAudience(JPush.alias('a@d.com'), JPush.tag('b@d.com')) // 不正常，只有前面的有效

// ---------------------------------------------------------------------------

.setAudience({tag:['b@d.com']}, {alias:['a@d.com']}) // 全部无效
.setAudience({tag:['b@d.com']}) // 正常
.setAudience({alias:['a@d.com']}) // 正常

// ---------------------------------------------------------------------------

也就是 tag, alias 不能同时在 .setAudience 的参数里。

**Comment by helperhaps** [comment]
请问你的所谓的有效是怎么判断的

**Comment by nodejscss** [comment]
是下面这样判断的：

有效：能收到推送消息
无效：不能收到推送消息

**Comment by nodejscss** [comment]
我贴的代码，你试一下就知道了。

**Comment by nodejscss** [comment]
刚才又试了一下，还是无效。

**Comment by helperhaps** [comment]
我肯定试过了，你是对 JPush 的 Audience 的概念不了解，建议先去读一下文档 https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#audience
