### ISSUE TITLE
Jpush v3.4.3

### ISSUE THREAD

**Issue by luanxuechao** [jpush/jpush-api-nodejs-client#43]
function toJSON () {
  this.payload.options = JUtil.extend({
    'sendno': generateSendno(),
    'apns_production': false
  }, this.payload.options)
  return JSON.stringify(this.payload)
}

为什么 Jpush  apns_production 一直是false  推不了正式环境

**Comment by helperhaps** [comment]
你需要设置 https://github.com/jpush/jpush-api-nodejs-client/blob/master/doc/api.md#pushpayload

看看这个函数 setOptions

**Comment by luanxuechao** [comment]
是的 写法问题 对不起
