### ISSUE TITLE
update node require, or recover the 'default parameter' usage

### ISSUE THREAD

**Issue by FunkySamuel37** [jpush/jpush-api-nodejs-client#45]
https://github.com/jpush/jpush-api-nodejs-client/blob/29c2703d917ca04043fc6d732326c4ec815ada3f/lib/JPush/JPush.js#L47
```javascript
function JPushClient (appKey, masterSecret, retryTimes, isDebug, readTimeOut = null, proxy = null) {
  if (!appKey || !masterSecret) {
    throw JError.InvalidArgumentError('appKey and masterSecret are both required.')
  }
 ...
}
```
default parameters is supported after node 6.4.0, but hey, you only need nodejs version greater than 0.12.0?
```
  "engines": {
    "node": ">=0.12"
  },
```

**Comment by helperhaps** [comment]
I am really sorry for that. But is that boring you? what is your nodejs version

**Comment by FunkySamuel37** [comment]
I am using v.4.6.2, already changed jpush-sdk version to 3.4.0

**Comment by helperhaps** [comment]
again，sorry for that. it will be fixed soon

**Comment by FunkySamuel37** [comment]
https://github.com/jpush/jpush-api-nodejs-client/commit/e59bbedc0a5ff943f84947591b69f2d2fc212ace

thx @helperhaps , that fixed my problem.
