### ISSUE TITLE
需要把tag_not从包里抛出来

### ISSUE THREAD

**Issue by zhouweicheng** [jpush/jpush-api-nodejs-client#49]
在PushPayloadloadAsync.js文件中  有tag_not这个方法   但是并没有抛出来给用户引用   麻烦抛出来下，类似于JPushAsync.js 里的
exports.tag_and = JModel.tag_and 
  增加一个
exports.tag_not = JModel.tag_not，
谢谢

![wx22db7o9p _a3jup 1k 5](https://user-images.githubusercontent.com/24772398/48826038-3ab28e80-eda4-11e8-9690-fdccccdbb859.png)
![8e5r_df9xs y r8 bp](https://user-images.githubusercontent.com/24772398/48826040-3dad7f00-eda4-11e8-8c47-22458a5f1036.png)

**Comment by helperhaps** [comment]
可以提个 PR 过来
