### ISSUE TITLE
SDK中JUtil上是否定义了isEmptyObject方法？

### ISSUE THREAD

**Issue by MessiLiu** [jpush/jpush-api-nodejs-client#52]
### SDK Version
![image](https://user-images.githubusercontent.com/16557699/50682727-c0d01f00-104a-11e9-9ebd-da6f3b7ae9b8.png)

### Error Info
![image](https://user-images.githubusercontent.com/16557699/50682700-a39b5080-104a-11e9-8da7-f370c653c2c3.png)

### So
然后我翻了一下PushPayload.js以及其它文件的源码，并没有发现哪里有将isEmptyObject定义在JUtil上面，是不是我没找到？

**Comment by MessiLiu** [comment]
### Code
我先通过setSingleSchedule、setSchedule等SDK方法创建了一个新的定时推送，这一步没问题，正常拿到了定时任务的schedule_id。然后在修改定时任务时，看到了上面的错误信息，修改任务的代码如下：
![image](https://user-images.githubusercontent.com/16557699/50683152-06411c00-104c-11e9-8e47-011259d6d4c3.png)

**Comment by MessiLiu** [comment]
### Fix
我先自己加了个polyfill
![image](https://user-images.githubusercontent.com/16557699/50684188-95036800-104f-11e9-84dd-ca58a6f8f4f5.png)
然后先这么用着，算是解决了
![image](https://user-images.githubusercontent.com/16557699/50684223-a77da180-104f-11e9-92cc-9994dda65b61.png)

**Comment by helperhaps** [comment]
很抱歉，被一个 PR 给删了 https://github.com/jpush/jpush-api-nodejs-client/pull/37

**Comment by MessiLiu** [comment]
哈哈～好的
