### ISSUE TITLE
missing 'style' in output from JPushAsync.android() if style is not 0

### ISSUE THREAD

**Issue by Oowomn** [jpush/jpush-api-nodejs-client#56]
for my case, I want to use big image picture style (style = 3) for the android notification. However, I cannot get any data with `bundle.getString(JPushInterface.EXTRA_BIG_PIC_PATH);` at onReceive() on android. Compared to the restful api documents, I found that the android notification data created by JPushAsync.android() is missing the field "style". If I add the style by myself `data.android.style = 3`. I can get the data from `bundle.getString(JPushInterface.EXTRA_BIG_PIC_PATH);` in android.

**Comment by helperhaps** [comment]
You can simply test it with the following code (please feel free to do any change you want):

```node
payload = client.push().setPlatform(JPush.ALL)
  .setAudience(JPush.ALL)
  .setNotification('Hi, JPush', JPush.ios('ios alert', 'happy', 5))

console.log(payload)
```

It will print what the payload is on earth. Then you can check where the problem is.
