### ISSUE TITLE
推送结果中返回 headers 结果

### ISSUE THREAD

**Issue by zlx** [jpush/jpush-api-nodejs-client#6]
根据最新文档：http://docs.jpush.cn/pages/viewpage.action?pageId=7864690

每个请求头里面会塞入

> 所有的 HTTP API Response Header 里都加了三项频率控制信息：
> 
> X-Rate-Limit-Limit：当前 AppKey 一个时间窗口内可调用次数
> X-Rate-Limit-Remaining：当前时间窗口剩余的可用次数
> X-Rate-Limit-Reset：距离时间窗口重置剩余的秒数

如果能在推送之后的回调里面返回这些信息，我们就可以根据这个信息来决定要不要继续推送，以避免过多的错误造成服务器过大的压力和业务端处理逻辑的复杂化。

如果可以，我愿意提供 patch

**Comment by plusmancn** [comment]
弱弱的问下，是不是，貌似现在还没有加进去？

**Comment by xiezefan** [comment]
@plusmancn  Sorry，一直忘记了。 囧，这几天我抽下时间重新维护起这个库....
