### ISSUE TITLE
TAG_PATH BUG

### ISSUE THREAD

**Issue by iroan** [jpush/jpush-api-nodejs-client#61]
[here](https://github.com/jpush/jpush-api-nodejs-client/blob/f9cf8b6a7dc0401192d9276626a91f1228c67e3d/lib/JPush/JPushAsync.js#L23)
此处的路径，添加'/', getTagList接口报错
不添加'/', addRemoveDevicesFromTag接口报错

**Comment by helperhaps** [comment]
已解决，请升级到 4.0.2
